version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard

root:
  handlers: [console]
  level: INFO

loggers:
  django:
    handlers: [console]
    level: INFO
    propagate: true
